version: '3'

services:
  app:
    restart: always
    build: .
    network_mode: 'host'
    command: python3 ./app.py
    #command: /bin/bash
    tty: true
    volumes:
      - /etc/machine-id:/etc/machine-id
      - ./:/home:z

